apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: exampleproject2
  name: exampleproject2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleproject2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: exampleproject2
    spec:
      containers:
        - image: polsoftex.azurecr.io/exampleproject2:latest
          name: exampleproject2
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: exampleproject2
  name: exampleproject2
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: exampleproject2
  type: ClusterIP
